stages:
  extract-data:
    cmd: tar -xf dataset/cifar-10-python.tar.gz --exclude='readme.html' --directory dataset/
    deps:
      - dataset/cifar-10-python.tar.gz
    outs:
      - dataset/cifar-10-batches-py
  convert-notebook:
    cmd: JUPYTER_DATA_DIR=$PWD/__pypackages__/3.8/share/jupyter/ pdm run jupyter nbconvert --to script train.ipynb
    deps:
      - train.ipynb
    outs:
      - train.py
  generate-hash:
    cmd: pdm run python hash_params.py
    deps:
      - hash_params.py
    outs:
      - params.yaml.sha
    params:
      - seed
      - epochs
  train:
    cmd: pdm run python train.py
    vars:
      - params.yaml.sha
    deps:
      - train.py
      - params.yaml.sha
      - dataset/cifar-10-batches-py
    outs:
      - experiment/${hash}/
    params:
      - seed
      - epochs
    metrics:
      - scores.json:
          cache: false
