stages:
  extract-data:
    cmd: tar -xf dataset/cifar-10-python.tar.gz --exclude='readme.html' --directory dataset/
    deps:
      - dataset/cifar-10-python.tar.gz
    outs:
      - dataset/cifar-10-batches-py
  convert-notebook:
    cmd: pdm run convert-notebook
    deps:
      - train.ipynb
    outs:
      - train.py
  train:
    cmd: pdm run train
    deps:
      - train.py
      - dataset/cifar-10-batches-py
    outs:
      - experiment/
    params:
      - seed
      - epochs
    metrics:
      - scores.json:
          cache: false
