stages:
  convert-notebook:
    cmd: pdm run convert-notebook
    deps:
      - train.ipynb
    outs:
      - train.py
  train:
    cmd: pdm run train
    deps:
      - train.py
      - dataset/cifar-10-batches-py
    outs:
      - experiment/
    params:
      - seed
      - epochs
    metrics:
      - scores.json:
          cache: false
